[package]
name = "hiveflow-core"
version = "0.1.0"
edition = "2024"

[dependencies]
hiveflow-macros = { path = "../hiveflow-macros" }
tokio = { version = "1.46.1", features = ["full"] }
async-trait = "0.1.88"
futures = "0.3.31"

[lib]
proc-macro = false